# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Tekton Controller
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_IMAGE: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.12.1
        TARGET_IMAGE: docker.pkg.github.com/jenkins-zh/gcr.io.mirror/controller:v0.12.1
      run: |
        docker login docker.pkg.github.com -u LinuxSuRen -p ${GITHUB_TOKEN}
        docker pull ${SOURCE_IMAGE}
        docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
        docker push ${TARGET_IMAGE}
    - name: Tekton Webhook
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SOURCE_IMAGE: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.12.1
        TARGET_IMAGE: docker.pkg.github.com/jenkins-zh/gcr.io.mirror/webhook:v0.12.1
      run: |
        docker login docker.pkg.github.com -u LinuxSuRen -p ${GITHUB_TOKEN}
        docker pull ${SOURCE_IMAGE}
        docker tag ${SOURCE_IMAGE} ${TARGET_IMAGE}
        docker push ${TARGET_IMAGE}
